### ISSUE TITLE
program not compiling when it is compiled with gcc, without the GPU support 

### ISSUE THREAD

**Issue by majumdararn** [iternlm/microtomodenoise#3]
I tried to compile the program with g++ without the involvement of GPU.

I followed the following procedure.
1) opened the iterNLM_v0.3/make_iternlm.sh file.
2) changed CUDA_COMPUTECAPABILITY to 0
3) closed the file and executed the following command in directory iterNLM_v0.3
     sh make_iternlm.sh

The program is not compiled and shows the following error. the full error is attached in the file.

g++: error: microtomodenoise/iterNLM_v0.3/Build/hdcommunication.o: No such file or directory
g++: error: microtomodenoise/iterNLM_v0.3/Build/iternlm_prepare.o: No such file or directory

[error.txt](https://github.com/iternlm/microtomodenoise/files/12185307/error.txt)

**Comment by majumdararn** [comment]
I tried to commit changes to the program but GitHub does not allow me to create new branches and commit changes. It forces me to fork the project.

Therefore I write the solution here.
1) In iterNLM_v0.3/Geometry/hdcommunication.h file add #include <math.h>
2) In iterNLM_v0.3/Geometry/iternlm_prepare.h file add #include <math.h>

This problem occurred because some functions were used from the math header file but the header file was not included.

Arnab

**Comment by iternlm** [comment]
> I tried to commit changes to the program but GitHub does not allow me to create new branches and commit changes. It forces me to fork the project.
> 
> Therefore I write the solution here.
> 
> 1. In iterNLM_v0.3/Geometry/hdcommunication.h file add #include <math.h>
> 2. In iterNLM_v0.3/Geometry/iternlm_prepare.h file add #include <math.h>
> 
> This problem occurred because some functions were used from the math header file but the header file was not included.
> 
> Arnab

Thank you for pointing that out. A known issue that arose with newer gcc-versions. I incorporated your changes.
